  
 </div>
 </div>
 </div>

  <script type="text/javascript">var plugin_path = '../assets1/plugins/';</script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
  <script type="text/javascript" src="../assets1/plugins/jquery/jquery-2.1.4.min.js"></script>
  <script type="text/javascript" src="../assets1/js/app.js"></script>
  <script type="text/javascript" src="../includes/function.js"></script>
  <script type="text/javascript" src="../includes/userscript.js"></script>

  <script src="../new_assets/theme/js/jquery.min.js"></script>
      <script>
          $(document).ready(function(){
                $('.nav a').each(function(index)
                {
                    if(this.href.trim() == window.location)
                    {
                        $(this).closest('li').addClass('active');
                        $(this).closest('.el_primary').addClass('active');
                    }

                });
                $(document).on('focus', '.select2.select2-container', function (e) {
                  if (e.originalEvent && $(this).find(".select2-selection--single").length > 0) {
                    $(this).siblings('select').select2('open');
                  } 
                });
            });

            loadScript(plugin_path + "datatables/js/jquery.dataTables.min.js", function()
            {
                loadScript(plugin_path + "datatables/js/dataTables.tableTools.min.js", function()
                {
                    loadScript(plugin_path + "datatables/dataTables.bootstrap.js", function()
                    {
                        loadScript(plugin_path + "select2/js/select2.full.min.js", function(){

                            var table = jQuery('.sample_5');

                            /* Set tabletools buttons and button container */

                            jQuery.extend(true, jQuery.fn.DataTable.TableTools.classes, {
                                "container": "btn-group pull-right tabletools-topbar",
                                "buttons": {
                                    "normal": "btn btn-sm btn-default",
                                    "disabled": "btn btn-sm btn-default disabled"
                                },
                                "collection": {
                                    "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
                                }
                            });

                            var oTable = table.dataTable({
                                "order": [
                                    [0, 'desc']
                                ],
                                "lengthMenu": [
                                    [10, 15, 20, -1],
                                    [10, 15, 20, "All"] // change per page values here
                                ],
                                "pageLength": 10, // set the initial value,
                                "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

                                "tableTools": {
                                    "sSwfPath": plugin_path + "datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
                                    "aButtons": [{
                                        "sExtends": "pdf",
                                        "sButtonText": "PDF"
                                    }, {
                                        "sExtends": "csv",
                                        "sButtonText": "CSV"
                                    }, {
                                        "sExtends": "xls",
                                        "sButtonText": "Excel"
                                    }, {
                                        "sExtends": "print",
                                        "sButtonText": "Print",
                                        "sInfo": 'Please press "CTR+P" to print or "ESC" to quit',
                                        "sMessage": "Generated by DataTables"
                                    }]
                                }
                            });

                            var tableWrapper = jQuery('#sample_5_wrapper'); // datatable creates the table wrapper by adding with id {your_table_jd}_wrapper
                            tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown

                        });
                    });
                });
            });
        
      </script>
      <script src="../new_assets/theme/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
      <script src="../new_assets/theme/js/ui-load.js"></script>
      <script src="../new_assets/theme/js/ui-jp.config.js"></script>
      <script src="../new_assets/theme/js/ui-jp.js"></script>
      <script src="../new_assets/theme/js/ui-nav.js"></script>
      <script src="../new_assets/theme/js/ui-toggle.js"></script>
      <script src="../new_assets/theme/js/ui-client.js"></script>
      <script src="../new_assets/theme/js/wizard.js"></script>
      <!-- <script src="../new_assets/theme/js/theme-setting.js" type="text/javascript"></script> -->
      <script src="../new_assets/theme/libs/jquery/zebra-datepicker/zebra_datepicker.min.js" type="text/javascript"></script>
      <script src="../new_assets/theme/libs/jquery/autocomplete/jquery.autocomplete.js" type="text/javascript"></script>
      <script src="../new_assets/theme/libs/jquery/ckeditor/ckeditor.js"></script>
      <script src="../new_assets/theme/js/custom.js" type="text/javascript"></script>
      <script src="../new_assets/theme/libs/jquery/tooltipster/js/tooltipster.bundle.min.js" type="text/javascript"></script>
    <!--   <script src="../new_assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script> -->
      <script src="../new_assets/plugins/select2/dist/js/select2.min.js"></script>
      <script src="../new_assets/javascript/main.js"></script>
      <!-- <script src="../new_assets/javascript/demo_popup.js"></script> -->
      <script src="../new_assets/javascript/copy_to_clip_board.js" type="text/javascript" ></script>
      <style type="text/css">
         .margin-zero
         {
         margin-left: unset !important;
         }
      </style>
      <!-- <script src="../new_assets/javascript/chart/chart.min.js"></script> -->
      <!-- <script src="../new_assets/javascript/ajax-dynamic-dashboard-user.js" type="text/javascript"></script> -->
      <!-- <script src="../new_assets/javascript/user_dashboard.js"></script> -->
      <link rel="stylesheet" href="../new_assets/css/owl.carousel.min.css"/>
      <link rel="stylesheet" href="../new_assets/theme/css/dashboard_profile.css"/>
      <style type="text/css">
         .new-members.panel {
         min-height: 314px;
         }
         .user-det > div .sponsor-details:nth-child(1) {
         padding-left: 20px;
         }
         .renew_upgrade:hover,.renew_upgrade:active ,.renew_upgrade:focus .view_user:hover {
         background: #55489c;
         color: #fff;
         }
         .mr-20 {
         margin-right:20px
         }
         .pl-2 {
         padding-left:5px
         }
         .vertical_line {
         border-right: 1px dotted #bfbfbf;
         }
         .rela-blog-cnt-title {
         font-size: 15px;
         text-align: center;
         background: #e4e4e433;
         padding: 10px;
         height: 52px;
         margin: auto 0;
         overflow: hidden;
         font-weight: 600;
         }
         .panel .h1.font-thin.h1 {
         font-weight: 400;
         color: #6c787f;
         }
         .rela-blog-img {
         border-radius: 0%;
         }
         .news_content {
         height: 80px;
         overflow: hidden;
         }
         .read_full_news {
         text-align: center;
         color: #857cc3;
         }
         .read_full_news a:hover, a:focus {
         color: #717d84;
         text-decoration: none;
         }
         .rela-blog-cnt a.read_full_news {
         float: right;
         border: 1px solid #857cc3;
         border-radius: 15px;
         padding: 2px 8px;
         font-size: 11px;
         }
         .padding_bottom_zero {
         padding-bottom:0 !important; 
         }
         .padding_top_zero {
         padding-top: 0 !important;
         }
         .news-carousel .item {
         border: 1px solid #eee;
         padding: 6px 4px;
         }
         .rela-blog-img {
         border: unset;
         }
         .view_user {
         border-radius:2px
         }
         @media screen and (max-width: 1199px) {
         .col-md-12 {
         float: unset;
         }
         .box::after, .box1::after, .box2::after, .box3::after {
         width: 141px;
         height: 112px;
         top: -23%;
         left: -22%;
         }
         .box::before, .box1::before, .box2::before, .box3::before {
         top: -43%;
         left: -8%;
         }
         }
         @media screen and (max-width: 800px) {
         .box::after, .box1::after, .box2::after, .box3::after {
         width: 141px;
         height: 112px;
         top: -27%;
         left: -40%
         }
         .box::before, .box1::before, .box2::before, .box3::before {
         top: -47%;
         left: -18%;
         }
         }
      </style>
      <script type="text/javascript">
         $(function () {
         // loadDatePicker();
         // loadTimePicker();
         // loadDateTimePicker();
         });
      </script>
   </body>
</html>